try {
    console.log(a);
} catch (error) {
    console.log('err', error);
} finally {
    console.log(222);
}

console.log(1234);